CREATE TABLE IF NOT EXISTS claimant (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    claimant_name VARCHAR(150) NOT NULL,
    birth_date DATE,
    nationality_id BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    maritalstatus_id BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    occupation VARCHAR(50),
    ctps VARCHAR(9) NOT NULL,
    serie_ctps VARCHAR(9) NOT NULL,
    rg VARCHAR(7) NOT NULL,
    orgao_rg VARCHAR(10) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    pis VARCHAR(50),
    address VARCHAR(255) NOT NULL,
    state_id BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    city_id BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    neighborhood VARCHAR(50) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    cep VARCHAR(10) NOT NULL,
    bank VARCHAR(50),
    agency VARCHAR(10),
    operation VARCHAR(10),
    account VARCHAR(20),
    accounttype_id BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    contact VARCHAR(255) NOT NULL,
    email VARCHAR(150),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (nationality_id) REFERENCES nationality (id),
    FOREIGN KEY (maritalstatus_id) REFERENCES marital_status (id),
    FOREIGN KEY (accounttype_id) REFERENCES account_type (id),
    FOREIGN KEY (state_id) REFERENCES state (id),
    FOREIGN KEY (city_id) REFERENCES city (id),
    UNIQUE (rg),
    UNIQUE (cpf)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
