CREATE TABLE IF NOT EXISTS lawsuit_status (
	id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    PRIMARY KEY (id),
   	UNIQUE (status)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
