CREATE TABLE IF NOT EXISTS lawsuit_phase (
	id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    phase VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
   	PRIMARY KEY (id),
    UNIQUE (phase)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
