DROP TABLE IF EXISTS state;
CREATE TABLE state (
  id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  code_uf BIGINT DEFAULT NULL,
  name VARCHAR(100) DEFAULT NULL,
  uf CHAR(2) DEFAULT NULL,
  region VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

