DROP TABLE IF EXISTS city;
CREATE TABLE city (
  id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  state_id BIGINT UNSIGNED NOT NULL,
  county_code BIGINT DEFAULT NULL,
  name VARCHAR(150) DEFAULT NULL,
  uf CHAR(2) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (state_id) REFERENCES state (id)
) ENGINE=InnoDB AUTO_INCREMENT=5597 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

